INSERT INTO client(client_id,ip_address,id,sr) VALUES('-1','asda','-1','0');
INSERT INTO queue(queue_id,queue_name) VALUES('-1','q');
INSERT INTO message(queue_id,rec_id,sen_id,chat,t) VALUES('-1',NULL,'-1','asdasasdasda dasdow aar eoyausd adiasod oashdoih',now());
INSERT INTO message(queue_id,rec_id,sen_id,chat,t) VALUES('-1',NULL,'-1','asdasasdasda dasdow aar eoyausd adiasod oashdoih',now());
INSERT INTO message(queue_id,rec_id,sen_id,chat,t) VALUES('-1',NULL,'-1','asdasasdasda dasdow aar eoyausd adiasod oashdoih',now());
INSERT INTO message(queue_id,rec_id,sen_id,chat,t) VALUES('-1',NULL,'-1','asdasasdasda dasdow aar eoyausd adiasod oashdoih',now());
INSERT INTO message(queue_id,rec_id,sen_id,chat,t) VALUES('-1',NULL,'-1','asdasasdasda dasdow aar eoyausd adiasod oashdoih',now());
INSERT INTO message(queue_id,rec_id,sen_id,chat,t) VALUES('-1',NULL,'-1','asdasasdasda dasdow aar eoyausd adiasod oashdoih',now());
INSERT INTO message(queue_id,rec_id,sen_id,chat,t) VALUES('-1',NULL,'-1','asdasasdasda dasdow aar eoyausd adiasod oashdoih',now());
INSERT INTO message(queue_id,rec_id,sen_id,chat,t) VALUES('-1',NULL,'-1','asdasasdasda dasdow aar eoyausd adiasod oashdoih',now());
INSERT INTO message(queue_id,rec_id,sen_id,chat,t) VALUES('-1',NULL,'-1','asdasasdasda dasdow aar eoyausd adiasod oashdoih',now());
INSERT INTO message(queue_id,rec_id,sen_id,chat,t) VALUES('-1',NULL,'-1','asdasasdasda dasdow aar eoyausd adiasod oashdoih',now());
INSERT INTO message(queue_id,rec_id,sen_id,chat,t) VALUES('-1',NULL,'-1','asdasasdasda dasdow aar eoyausd adiasod oashdoih',now());
INSERT INTO message(queue_id,rec_id,sen_id,chat,t) VALUES('-1',NULL,'-1','asdasasdasda dasdow aar eoyausd adiasod oashdoih',now());
INSERT INTO message(queue_id,rec_id,sen_id,chat,t) VALUES('-1',NULL,'-1','asdasasdasda dasdow aar eoyausd adiasod oashdoih',now());
INSERT INTO message(queue_id,rec_id,sen_id,chat,t) VALUES('-1',NULL,'-1','asdasasdasda dasdow aar eoyausd adiasod oashdoih',now());
INSERT INTO message(queue_id,rec_id,sen_id,chat,t) VALUES('-1',NULL,'-1','asdasasdasda dasdow aar eoyausd adiasod oashdoih',now());
INSERT INTO message(queue_id,rec_id,sen_id,chat,t) VALUES('-1',NULL,'-1','asdasasdasda dasdow aar eoyausd adiasod oashdoih',now());
INSERT INTO message(queue_id,rec_id,sen_id,chat,t) VALUES('-1',NULL,'-1','asdasasdasda dasdow aar eoyausd adiasod oashdoih',now());
